name: plaint_or_tweet
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - tqdm
  - ipykernel
  - pandas
  - pytorch
  - spacy
  - spacy-lookups-data
  - spacy-model-en_core_web_sm
  - pip
  - pip:
    - urlextract
